#!/bin/sh

set -e

if [ "$1" != "configure" ]; then
    exit 0
fi

# Automatically added by dh_installinit/12.1.1
if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
	if [ -x "/etc/init.d/unit" ]; then
		update-rc.d unit defaults >/dev/null
		invoke-rc.d unit start || exit 1
	fi
fi
# End automatically added section


exit 0
